### ISSUE TITLE
logica fetch personen en instellingen 

### ISSUE THREAD

**Issue by oliviervd** [brechtvdv/adlib2eventstream#17]
overkoepelende vraag; is het mogelijk om onderscheid te maken tussen persoon en instelling. 
personen onder OSLO.persoon en instellingen onder OSLO.organisatie? 

**Design Museum Gent  + STAM + Industriemuseum**:
persoon >  naam.soort = vervaardiger AND naam.soort = persoon AND. naam.status = descriptor 
instelling > naam.soort = vervaardiger AND naam.soort = instelling AND. naam.status = descriptor 

**Huis van Alijn**: 
persoon > naam.soort = persoon OR naam.soort = vervaardiger AND naam.status  = descriptor 
instelling > naam.soort = instelling OR naam.soort = vervaardiger AND naam.status  = descriptor 

**Archief Gent**:
persoon > naam.soort = persoon AND naam.status  = descriptor 
instelling > naam.soort = instelling AND naam.status  = descriptor

**Comment by brechtvdv** [comment]
op naam.soort checken is volgens mij niet voldoende om te zeggen dat het om een persoon gaat
bv: priref=530024212 (Cruyt (familie)) zou een persoon zijn, maar in feite is dit eerder een concept

**Comment by oliviervd** [comment]
klopt.. die edge cases zijn er wel..

**Comment by brechtvdv** [comment]
Fix https://github.com/StadGent/node_service_adlib-backend/commit/60086a206422751d500b3cca0940a40ea196a827
