### ISSUE TITLE
Change URI strategy

### ISSUE THREAD

**Issue by brechtvdv** [brechtvdv/adlib2eventstream#5]
Allow to define URI template that looks as follows:
https://stad.gent/id/{type}/{collectie}/{pid}

**Comment by brechtvdv** [comment]
- Catalogus: https://lodi.ilabt.imec.be/coghent/id/datasetcatalogus/coghent
-> https://stad.gent/id/datasetcatalogus/coghent (zonder pid?)

- Dataset / tree:Collection: https://lodi.ilabt.imec.be/coghent/dmg/id/dataset/206d69c469151306d018140d6a5345e6
-> https://stad.gent/id/dataset/dmg/206d69c469151306d018140d6a5345e6

- Versie object: https://lodi.ilabt.imec.be/coghent/dmg/id/objecten/530026088/2021-02-03T15:48:18.091Z
-> https://stad.gent/id/mensgemaaktobject/dmg/530026088/2021-02-03T15:48:18.091Z
(/ref/ref-versie)

- Persistent object: http://example.org/id/objecten/530026088
-> https://stad.gent/id/mensgemaaktobject/dmg/530026088

**Comment by nvdk** [comment]
For the catalog https://stad.gent/id/dcat/coghent/ would be preferred, as that's more in line with the other catalogs.
Other suggestions are fine. What does dmg refer to?

**Comment by oliviervd** [comment]
dmg refers to Design Museum Gent_
