### ISSUE TITLE
revise type:persoon should be type:instelling? 

### ISSUE THREAD

**Issue by oliviervd** [brechtvdv/adlib2eventstream#7]
https://github.com/brechtvdv/adlib2eventstream/blob/09a5654c3fa20fb676eaa1b3e957259e1f049c6c/lib/mappers/utils.js#L161

examples; 

`{\'@type\': \'ConceptueelDing\', \'ConceptueelDing.heeftCreatie\': {\'@type\': \'Creatie\', \'Gebeurtenis.tijd\': {\'Periode.begin\': \'1957\', \'Periode.einde\': \'1957\'}, \'Activiteit.uitgevoerdDoor\': {\'@type\': \'Persoon\', \'volledigeNaam\': "Compagnie de L\'Esthétique Industrielle (CEI)"},\'Gebeurtenis.plaats\': \'Parijs\'}}
`

**Comment by brechtvdv** [comment]
Hmm in jouw voorbeeld is het inderdaad een instelling, maar het kan evengoed een persoon soms zijn?

**Comment by oliviervd** [comment]
gaat dit niet over productie dus producenten?

**Comment by brechtvdv** [comment]
Jouw voorbeeldje is de creatie van het ontwerp (conceptueel ding)

**Comment by brechtvdv** [comment]
ontwerp of productie kan zowel door personen als organisaties dus zijn?
